# Matrix of required of OS and Swift releases
matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
      services: docker
      env: DOCKER_IMAGE_TAG=swift:5.4.0-bionic ONLY_RUN_SWIFT_LINT=no USE_APT_GET=yes
    - os: linux
      dist: bionic
      sudo: required
      services: docker
      env: DOCKER_IMAGE_TAG=swift:5.4.0-focal ONLY_RUN_SWIFT_LINT=no USE_APT_GET=yes
    - os: linux
      dist: bionic
      sudo: required
      services: docker
      env: DOCKER_IMAGE_TAG=swift:5.4.0-amazonlinux2 ONLY_RUN_SWIFT_LINT=no USE_APT_GET=no
    - os: linux
      dist: bionic
      sudo: required
      services: docker
      env: DOCKER_IMAGE_TAG=swift:5.4.0-centos8 ONLY_RUN_SWIFT_LINT=no USE_APT_GET=no
      
    - os: linux
      dist: bionic
      sudo: required
      services: docker
      env: DOCKER_IMAGE_TAG=swift:5.3.3-bionic ONLY_RUN_SWIFT_LINT=no USE_APT_GET=yes

    - os: linux
      dist: bionic
      sudo: required
      services: docker
      env: DOCKER_IMAGE_TAG=swift:5.2.5-bionic ONLY_RUN_SWIFT_LINT=no USE_APT_GET=yes

    # Verify next version of Swift (5.5)
    - os: linux
      dist: bionic
      sudo: required
      services: docker
      env: DOCKER_IMAGE_TAG=swiftlang/swift:nightly-5.5-amazonlinux2 ONLY_RUN_SWIFT_LINT=no USE_APT_GET=no

    # Use a docker image that contains the SwiftLint executable the verify the code against the linter.
    - os: linux
      dist: bionic
      sudo: required
      services: docker
      env: DOCKER_IMAGE_TAG=bytesguy/swiftlint:0.39.2 ONLY_RUN_SWIFT_LINT=yes USE_APT_GET=no

before_install:
  - docker pull $DOCKER_IMAGE_TAG

script:
  - docker run -v ${TRAVIS_BUILD_DIR}:/package ${DOCKER_IMAGE_TAG} /bin/bash -c "/package/CITests/run $ONLY_RUN_SWIFT_LINT $USE_APT_GET"
